version: '3.1'

networks:
  network_local:
    external: true

services:
  api:
    build: ./backend
    image: node:alpine
    volumes:
      - ./backend:/app
    ports:
      - 3333:3333
    depends_on:
      - database
    networks:
    - network_local

  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=docker
    ports:
      - 3306:3306
    networks:
    - network_local

  web:
    build: ./frontend
    image: node:13-alpine
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
    - network_local